services:
  ollama:
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-rocm}
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION-11.0.0}'
      - 'OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE--1}'
      - 'OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION-1}'
      - 'OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL-2}'
